### PR TITLE
napi-rs direct bundle

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

The additional dependencies and requirements by node-gyp made it worthwhile it explore alternatives. One such option is to bundle the built files directly. As part of this exploration, I also converted to napi-rs which has seen much more attention and I suspect will help us reduce the file size as well.

## Approach

Converted to napi-rs, and copy the built files directly into the dist folder. I also explored the removal of the separate `killer.exe`, but we seem stuck with that. I also switched to windows-rs which is being supported by Microsoft directly.

Bundling the binary/.node files directly removes all package dependencies and will have roughly equivalent download size (compared to the previous iteration including it's dependencies).
image

### CODE REVIEW

**Review by cowboyd — APPROVED** [review]
Excellent!

**Comment by jbolda** [comment]
thanks! I presume you agree that a v3 makes sense for this? I think the process is to create a v3 branch, change the PR to target that, and then change the default branch?

**Comment by cowboyd** [comment]
@jbolda I'm ok with a v3 release, although if the JS api has not changed at all, does it really warrant a major version bump?

**Comment by jbolda** [comment]
@cowboyd Honestly I could be convinced of any type of bump. I suppose minor or major would probably be a better fit, but even patch could be justified? (At a base level, it is fixing vulns.) The packaging changed quite a bit and there is potential for breakage, but since the API didn't change, any breaks would really be considered a bug. That also sounds much like a minor bump.

I don't know, your thoughts?

**Comment by cowboyd** [comment]
@jbolda actually, I am convinced by your logic that patch is actually putting the money where our mouth is.

**Comment by jbolda** [comment]
@cowboyd what do you think about a minor bump here and a patch bump downstream in effection? I think I am getting stuck on there being so much change here that patch doesn't quite represent that to me.

**Comment by cowboyd** [comment]
@jbolda sounds good

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
