### PR TITLE
node-pre-gyp 1.0.7 to fix security notification

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

Some upstream deps of node-pre-gyp have security fixes that have been fixed.

## Approach

Increment to the latest to get these changes, and avoid notifications.

### CODE REVIEW

**Comment by jbolda** [comment]
The test failure in effection looks like an extra new line? I can't reproduce it locally on my windows box. Any thoughts?

**Review by cowboyd — APPROVED** [review]
🥳 🕺🏻

**Comment by jbolda** [comment]
This package now has a newer update. Going to upgrade it in this PR tonight.

Also, I have noticed the new line show up in the Github Actions windows box in covector as well. It is a `\r` that sneaks in there with whatever shell the windows box is running things with. With the updated tests in https://github.com/thefrontside/effection/pull/628, curious if it is going to be resolved (since I noticed it there and wrote the tests to consider it).

**Comment by jbolda** [comment]
Closing in favor of #39.

**Pull request closed without merging**
