### PR TITLE
Upload node 16 binary (attempt #2)

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation

#25 did not turn out the way we had hoped

## Approach (Updated ✨)

- The tests were passing in #25 but we weren't actually using the node versions in the matrix (via volta). So I fixed that in the test workflow and ~I'm also running the upload workflow but without any of the prechecks and without creating a release nor uploading the binaries to see if it actually builds using `node-pre-gyp`~.
  - See successful build of 10, 12, 14, 16 [here](https://github.com/thefrontside/ctrlc-windows/actions/runs/838560764)
    - Upload workflow was reverted with 16 added so that it runs on push on main branches again after confirming it works in this PR
- Bumped `neon`, `neon-build`, and `neon-cli` to latest in order to build in node 16.
- Updated CHANGELOG and bumped package to 1.0.5 to trigger upload and release.

## TODOs
- ⚠️ The windows tests in Github Actions will sometimes fail which requires me to re-run the test workflow until it passes.
  - The windows tests from commit [a04d4f5](https://github.com/thefrontside/ctrlc-windows/pull/28/commits/a04d4f5460e9ebd1b3f4d7a48e572937983de9c1) ran [successfully](https://github.com/thefrontside/ctrlc-windows/actions/runs/838560765)
  - And the windows tests for the last commit is failing even though the only changes are to a [separate workflow](https://github.com/thefrontside/ctrlc-windows/pull/28/commits/f70f90da50b9d4875e9e0348ac4d64c0ff8d5336), the [package version of `ctrlc-windows`](https://github.com/thefrontside/ctrlc-windows/pull/28/commits/02d3ec159cc1d8fe1264cf957104861e3a903aac), and the [CHANGELOG](https://github.com/thefrontside/ctrlc-windows/pull/28/commits/7b52d55e1a30e75b7fe637f41fa0262bd0867efb).

### CODE REVIEW

**Comment by minkimcello** [comment]
@cowboyd @jbolda Do we really need node 15? Seems [others](https://github.com/neon-bindings/neon/issues/589#issuecomment-735395787) have had issues building in node 15 too.

**Comment by jbolda** [comment]
I think it is pretty common to not support the odd number versions once the even number version is released.

**Comment by minkimcello** [comment]
@jbolda I can't figure out how windows node 16 tests passed before and now it can't. 🤦 All that's changed is the changelog, reverting the upload workflow to run on push instead of pull, and bumping the ctrlc-windows package version.

**Comment by minkimcello** [comment]
# 😠

**Comment by jbolda** [comment]
> @jbolda I can't figure out how windows node 16 tests passed before and now it can't. 🤦 All that's changed is the changelog, reverting the upload workflow to run on push instead of pull, and bumping the ctrlc-windows package version.

I think we weren't running tests on node 16 before. It didn't seem to work on `0.5` on my end, but it's possible the `0.8` might. We can try it locally on my computer if you think that might help.

**Comment by minkimcello** [comment]
> > @jbolda I can't figure out how windows node 16 tests passed before and now it can't. 🤦 All that's changed is the changelog, reverting the upload workflow to run on push instead of pull, and bumping the ctrlc-windows package version.
> 
> I think we weren't running tests on node 16 before. It didn't seem to work on `0.5` on my end, but it's possible the `0.8` might. We can try it locally on my computer if you think that might help.

The tests run successfully on node 16 (or I guess I should say it builds successfully because it's the build step that's failing) if the version of ctrcl-windows in package.json is `<=1.04`. Is there a part in the build process where it pulls from npm by any chance?

**Comment by minkimcello** [comment]
Closing in favour of #26. Node 16 with neon is a no go.

**Pull request closed without merging**
