### PR TITLE
Add node 15 and 16 for binary release workflow

### LINKED ISSUE #21: Add binary release for node 15, 16
The fix is in for neon and node 15, so we should be able to make a binary release for that version.

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation

To resolve #21.

## Approach

Added `15` and `16` to the `node-version` matrix.

No changeset because we're not making changes to the package itself.

### CODE REVIEW

**Review by cowboyd — APPROVED** [review]

**Review by cowboyd — CHANGES_REQUESTED** [review]
We should have a changeset right so that 1.0.4 gets releasedi with these versions? Also, it should be in the changelog that we're now releasing it with extra binaries

**Comment by minkimcello** [comment]
> We should have a changeset right so that 1.0.4 gets releasedi with these versions? Also, it should be in the changelog that we're now releasing it with extra binaries

Wouldn't the `upload-binaries` workflow run and add the new binaries to 1.0.3?

**Comment by cowboyd** [comment]
> > We should have a changeset right so that 1.0.4 gets releasedi with these versions? Also, it should be in the changelog that we're now releasing it with extra binaries
> 
> Wouldn't the `upload-binaries` workflow run and add the new binaries to 1.0.3?

I was thinking the same thing, but then wondering if that counts as a patch. What it will do aside, What do we think it should do?

**Comment by minkimcello** [comment]
> I was thinking the same thing, but then wondering if that counts as a patch. What it will do aside, What do we think it should do?

I suppose having it in the changelog would be helpful if in case anybody struggles to use an earlier version of this package with node 15 or 16. But since the package hasn't changed and we don't really need it to go through the whole release workflow to publish an identical package, I could cheat and just modify the changelog manually.

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
